### ISSUE TITLE
[Feature request] copy/paste secret

### ISSUE THREAD

**Issue by douze-bis** [fcrespo82/vscode-secretlens#1]
Hi!
Secretlens is great :)

Is it possible to add a feature to copy/paste the secret in the lens without needing to decrypt it first ?

My use case it using VSCode as a vault for passwords to Internet sites : I'd like to keep the editor and file encrypted and still have the possibility to copy/paste the passwords directly from VSCode to my browser.

Cheers!

**Comment by fcrespo82** [comment]
Hmm, this could me nice. I'll dig into it this week.

Thanks for the feedback!

**Comment by fcrespo82** [comment]
Published on version 1.3.0.

If you have any problems please open a bug report!
