### ISSUE TITLE
Can no longer decrypt

### ISSUE THREAD

**Issue by douze-bis** [fcrespo82/vscode-secretlens#9]
Hi!

It seems I can no longer decrypt the secrets in my secretlens-protected files.
Quite a bad feeling...

This may be related to the last update (2.1.0) ?

Is there a way to re-install a previous version of the secretlens extension ?

Frederic

**Comment by fcrespo82** [comment]
I will need to investigate this properly, but you can install an older version of the plugin following the steps from the site https://code.visualstudio.com/updates/v1_30#_install-previous-versions

But please, send me more info about the bug. You were decrypting a hole file? Just a few lines? What kind of content (plain text, json, xml)?

**Comment by douze-bis** [comment]
Apparently it is not a problem with a secretlens update.
It seems to be a problem with VSC update. Secretlens seems not to work at all with VSC Version 1.36.1 2213894ea0415ee8c85c5eea0d0ff81ecc191529  2019-07-08T22:48:28.193Z for MacOS.
Version 1.36.1 seems to break all versions of secretlens, even starting from a clean sheet.

**Comment by douze-bis** [comment]
I was just trying to fetch one single secret from a .md file.
Yes, thank you for the hint for reverting to a previous version of secretlens -- and actually I had found it in // :)

**Comment by douze-bis** [comment]
I found that by reverting to a January version of VSC, I was able to make secretlens working again.
Now I have to see how I can prevent VSC to automatically update to the last version of VSC because when it does, it breaks secretlens.

**Comment by just4t** [comment]
Confirmed that SecretLens also fails on the version of VSC version 1.36.1 (Windows10) ... It seems that the issue could be a big problem for those of us who have been using it for a long time if it can not be solved. 
* Waiting dev. feedback before to downgrade VSC ( or to build an older version of VSC over a Virtual machine with a windows guest) to get, at least, the files back (decrypted). Thanks in advance!

**Comment by fcrespo82** [comment]
@just4t My initial investigation shows that the problem is the node version that vscode is running deprecated some of the api I was using. I already have a patch for the extension. Just need a few more tests and should be able to release a patch later today!

**Comment by just4t** [comment]
@fcrespo82 Excellent news! Thanks alot for your efforts and fast feedback :)

**Comment by douze-bis** [comment]
👍

**Comment by fcrespo82** [comment]
Version 2.1.3 should be up soon with a fix for this. Please let me know if it persists.

**Comment by just4t** [comment]
[SOLVED] Confirmed your recently released _SecretLens 2.1.3_ version, solved the reported issue over VSC version 1.36.1 (Windows10)_

**Comment by douze-bis** [comment]
Confirmed here too.
👌

**Comment by netalex** [comment]
i have

command 'secretlens.[any command]' not found

with SL v2.2.2 and VSCode v1.86.0

it is linked?
